name: Build and Deploy
on: 
 workflow_dispatch:
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        xcode-version: latest-stable
    - name: Checkout secrets
      uses: actions/checkout@v2
      with:
          repository: 'herowio/herow-api-secrets'
          token: ${{ secrets.PAT_READ_PRIVATE_REPO }}
          path: secrets
    - name: copy platform-secrets.plits
      run: cp secrets/platform-secrets.plist ./herow-sdk-ios/connection/platform-secrets.plist;
       echo "RELEASE_VERSION=v$(/usr/libexec/PlistBuddy -c "Print :sdkVersionText" herow-sdk-ios/Info.plist)" >> $GITHUB_ENV
    - name: pod installation
      run: | 
          rm -rf Pods;
          rm -rf Podfile.lock;
          rm -rf herow_sdk_ios.xcworkspace;
          pod install;
    - name: Start build
      run: | 
          rm -rf output
          xcodebuild -workspace herow_sdk_ios.xcworkspace -scheme build -destination "platform=iOS Simulator,name=iPhone 11 Pro" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO ENABLE_BITCODE=YES OTHER_CFLAGS="-fembed-bitcode" BITCODE_GENERATION_MODE=bitcode 
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name:  ${{ env.RELEASE_VERSION }} #${{ github.ref }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
    - name: Upload Release herow_sdk_ios.xcframework dsym
      id: upload-xcframework-dsym
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: output/herow_sdk_ios.xcframework.dSYM.zip
          asset_name: herow_sdk_ios.xcframework.dSYM.zip
          asset_content_type: application/zip         
    - name: Upload Release herow_sdk_ios.xcframework
      id: upload-xcframework
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: output/herow_sdk_ios.xcframework.zip
          asset_name: herow_sdk_ios.xcframework.zip
          asset_content_type: application/zip
   
    - name: Deploy podspec
      env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      run: |
         REPO_DIRECTORY=Specs
         cd output;
         pod repo add herowio https://user:$API_TOKEN_GITHUB@github.com/herowio/$REPO_DIRECTORY;
         pod repo push herowio Herow.podspec
         cd ../..;
         
    - name: Deploy Package.swift
      env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      run: |
         REPO_DIRECTORY=herow-sdk-swiftPackage
         cd output;
         git clone https://user:$API_TOKEN_GITHUB@github.com/herowio/$REPO_DIRECTORY;
         pwd;ls;
         cp -r Package.swift $REPO_DIRECTORY/Package.swift ;
         cd $REPO_DIRECTORY;
         git add .;
         git commit -m "deploy version $RELEASE_VERSION";
         git push;
         git tag  "$RELEASE_VERSION";
         git push --tags;
         cd ../..;  
